const { setEngine } = require("crypto");
const { waitForDebugger } = require("inspector");

Feature('Overview');

Scenario('Checking Portal Overview', ({ I }) => {
I.amOnPage('https://propzy.vn');
I.wait(1);
I.see('Kết nối mọi nhu cầu về bất động sản', 'h1');
I.wait(1);
I.scrollPageToBottom();
I.see('Tìm nhà đất theo khu vực', 'h2');
I.wait(1);
I.scrollPageToTop();
I.wait(1);
I.amOnPage('https://propzy.vn/mua/bat-dong-san/hcm/quan-5?page=0&tags=hcm-quan-5&type=mua');
I.wait(1);
I.see('Mua Bán Bất Động Sản tại Quận 5', 'h1');
I.wait(1);
I.scrollPageToBottom();
I.see('BẤT ĐỘNG SẢN QUẬN LÂN CẬN', 'h2');
I.wait(1);
I.see('BẤT ĐỘNG SẢN THEO PHƯỜNG', 'h2');
I.wait(1);
I.scrollPageToTop();
I.wait(1);
I.amOnPage('https://propzy.vn/thue/bat-dong-san/hcm/quan-5?page=0&tags=hcm-quan-5&type=thue');
I.wait(1);
I.see('Cho Thuê Bất Động Sản tại Quận 5', 'h1');
I.wait(1);
I.scrollPageToBottom();
I.see('BẤT ĐỘNG SẢN QUẬN LÂN CẬN', 'h2');
I.wait(1);
I.see('BẤT ĐỘNG SẢN THEO PHƯỜNG', 'h2');
I.wait(1);
I.scrollPageToTop();
I.wait(1);
I.amOnPage('https://propzy.vn/du-an/hcm/quan-5?listingTypeId=1&page=0&tags=hcm-quan-5&type=du-an');
I.wait(1);
I.see('Danh Sách Các Dự Án Bất Động Sản tại Quận 5', 'h1');
I.wait(1);
I.scrollPageToBottom();
I.see('DỰ ÁN QUẬN LÂN CẬN', 'h2');
I.wait(1);
I.scrollPageToTop();
I.wait(1);
});